// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmxqcklcitlfrxsgbxjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteHFja2xjaXRsZnJ4c2dieGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjIwOTgsImV4cCI6MjA2ODkzODA5OH0.yiAGJAgmAD1w2RKl5Krck44fteon665uNn0y6vojfNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});